version: "2"

plugins:
  sonar-python:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  bandit:
    enabled: true

exclude_patterns:
  - ".pytest_cache/"
  - ".idea/"
  - ".vscode/"
  - "test_rosters/"
  - "**/static/"
  - "**/*.ros"
  - "**/*.rosz"
  - "**/__init__.py"
  - "**/*.xml"
  - "**/*.txt"
  - "**/*.yml"
  - "**/*.iml"
  - "Pipfile"
  - "Pipfile.lock"
  - ".gitignore"
  - "README.md"
  - "setup.cfg"
  - "Dockerfile"
  - "app/tests"
  - "app/constants.py"
  - "**/*_test.py"
  - "mypy_cache"
