repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ./.venv/bin/ruff
        args: 
          - check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: ruff-format
        name: ruff-format
        entry: ./.venv/bin/ruff
        args: 
          - format
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: ./.venv/bin/mypy
        args: 
          - src
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true