# file: .github/workflows/preview.yaml
name: preview

on:
  pull_request:
    branches:
      - main
  push:
    tags-ignore:
      - "*.*"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO }}
          url: ${{secrets.OKTETO_URL}}
      - name: "Deploy the preview environment"
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: pr-${{ github.event.number }}
          scope: global
          timeout: 15m
