name: Rollback Release

on:
  push:
    tags:
      - "*.*"
      
jobs:
  rollback:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@master
      
      - name: "Setup Kubectl"
        uses: azure/setup-kubectl@v2.0
      
      - name: "Set Context"
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Get previous release tag
        uses: SOLIDSoftworks/semver-tags@1.0.3
        id: prevtag
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          default-version: '1.7.5'
          dry-run: true
      
      - name: "Install Flux"
        run: curl -s https://fluxcd.io/install.sh | sudo bash
      
      - name: "Suspend Dataslate Deployments"
        run: flux suspend image repository dataslate-repo
      
      - name: "Roll back deployment"
        run: flux create image policy dataslate-policy --image-ref=dataslate-repo --select-semver=${{ steps.prevtag.outputs.previous-version }}



    
